### ISSUE TITLE
الجرد بالمحصل بدلا من المسار

### ISSUE THREAD

**Issue by mashh2017** [mashhu/Hand-Held#11]
تم تعديل شاشة الجرد ليكون بالمحصل بدلا من المسار 
need mas server version >=11.2

**Comment by mashh2017** [comment]
تم تنمفيذ

**Comment by ahmed-2017** [comment]
ممكن ال معاه التعديل دا يبعته عشان كان مطلوب ف الفيوم

**Comment by mohamed2020** [comment]
هل الجرد بالمحصل فقط في الشاشة الجديدة ام للمستخدم الاختيار بين الجرد بالمحصل والجرد بالمسار؟
