### ISSUE TITLE
version 11.3 comments and logs place

### ISSUE THREAD

**Issue by mashh2017** [mashhu/Hand-Held#16]
https://drive.google.com/file/d/0B508huxIddjfajdIcHJLWU5qcEU/view?usp=sharing_eil&ts=5945bda9

**Comment by mashh2017** [comment]
اهم النقاط
1- الجرد بالمحصل او المسار
2- المتوسط

**Comment by mohamed2020** [comment]
لو فيه فاتورة غير تابعة للمسار الذي يتم جرده هل تظهر رسالة لها ام لا؟

**Comment by mashh2017** [comment]
يوجد bug اثناء ارسال القراءات 
حلها
استبدل الملف في النسخة 11.3

https://drive.google.com/file/d/0B508huxIddjfdEp4S3NkY1BHOXc/view?usp=sharing

**Comment by mohamed2020** [comment]
انا نزلت النسخة 11.3 في فرع ساحل سليم وبدأ شغل عليها وكان عندهم سجل التوريدات باليوم في النسخة القديمة اخدته وضفته في الجديدة .
ده الجزء الخاص به في 
package
,
                 {
                     "ReportName": "deposits_new",
                     "ReportTitle": " سجل التوريدات باليوم",
                     "ReportTemplateUrl": "deposits_new.html",
                     "ReportDataSources": [
                         {
                             "SourceName": "deposits_new",
                             "SourceAlias": "walks",
                             "SourceUri": "Reports/Get",
                             "Filter": "table=STATM_DEPOSITS &$filter=DELIVERY_DATE ge datetime{{tfrom}}",
                             "InhirentSecurity": true,
                             "Parameters": [
                                {
                                    "Id": "tfrom",
                                    "Bind": "tfrom",
                                    "Operator": "eq",
                                    "Required": true,
                                    "Message": "من فضلك ادخل التاريخ ",
                                    "Type": "string"
                                }
                               
                             ]
                         }
                     ]
                 }
وده الhtml code
<mas-report>
    <mas-report-body>
        <mas-html-url-report-widget class="hidden" order="0" tmpl-url="reps/header.html">
        </mas-html-url-report-widget>
        <mas-html-report-widget order="1" source="walks">
            <div style="text-align:center;align-content:center;font-size:16px;font-weight:bold;text-decoration:underline;padding:10px" class="report-title"><span>التوريدات </span><span> في {{tfrom|date:'dd-MM-yyyy'}}</span></div>
            <div class="input-group no-print">
                <span>التاريخ</span>
                <input type="date" ng-model="$root.tfrom" />
                
                <button class="btn-success" ng-click="load()">تحميل</button>
            </div>
            <table class="table table-bordered table-condensed">
                <thead>
                    <tr class="label-default">
                        <th  style="max-width:30px">م</th>
                        <th  style="max-width:150px;" ng-click="walks=(walks | orderBy :'BILLGROUP')"><span class="fa fa-arrow-down success"></span> اسم المحصل</th>
                        <th >تاريخ التوريد</th>
                        <th >عدد الفواتير</th>
                        <th >المبلغ المورد</th>
                        <th >رقم القسيمة</th>
                        <th >رقم العملية</th>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-repeat="book in walks " ng-class-even="'alt-row'" ng-dblclick="showInfo(book)">
                        <td>{{$index+1}}</td>
                        <td>{{book.DELIVERY_MAN}}</td>
                        <td>{{book.DELIVERY_DATE}}</td>
                        <th>{{book.COUNT}}</th>
                        <th>{{book.AMOUNT}}</th>
                        <th>{{book.RECEIPT_NO}}</th>
                        <th>{{book.DEPOSIT_ID}}</th>
                    </tr>
                    <tr class="success print-summary-row" ng-show="walks.length>0">
                        <td colspan="3">الاجمالي</td>
                        <th>{{walks | Sum:'COUNT'}}</th>
                        <th>{{walks | Sum:'AMOUNT'}}</th>
                        <th></th>
                        <th></th>
                    </tr>
                </tbody>
            </table>
        </mas-html-report-widget>
    </mas-report-body>
</mas-report>

**Comment by mashh2017** [comment]
Mohammed this because wrong in report syntax

**Comment by mashh2017** [comment]
خطا اثناء نقل البيانات من الوحدة

الحل استبدال الملف المرفق
https://drive.google.com/open?id=0B508huxIddjfTlp1U2hiTzFMd00

**Comment by mashh2017** [comment]
https://github.com/mashh2017/Hand-Held/issues/17

**Comment by mohamed2020** [comment]
مشكلة في شاشة الجرد
invalid column name 'error message'
