### ISSUE TITLE
screen shoot for error while sending data 11.3 & 11.1

### ISSUE THREAD

**Issue by mashh2017** [mashhu/Hand-Held#17]
![photo from hasnmhmd77](https://user-images.githubusercontent.com/29061715/27432012-cc65a396-574e-11e7-90a9-55a0242051d2.jpg)

**Comment by mashh2017** [comment]
https://drive.google.com/open?id=0B508huxIddjfTlp1U2hiTzFMd00

**Comment by mashh2017** [comment]
should be closed after test

**Comment by osamamohammed731** [comment]
**Tested and working**.
issue solved you can close it
