### ISSUE TITLE
مشكلة في شاشة الجرد في mas 11.3

### ISSUE THREAD

**Issue by mohamed2020** [mashhu/Hand-Held#18]
![19578245_1899549550365387_1717595890_n](https://user-images.githubusercontent.com/6282249/27630649-65553412-5bf6-11e7-88b2-8b619963a2a0.jpg)

**Comment by mohamed2020** [comment]
اول ما بفتح شاشة الجرد بتطلع لي الرسالة دي اخر سطهر فيها بيقول invalid column name error message

**Comment by mohamed2020** [comment]
ENTITY COMMAND EXECUTION EXCEPTION EXCEPTION ON : INVALID COLUMN NAME "ERROR_MESSAGE "

**Comment by mohamed2020** [comment]
كان في مشكلة في وحدة وهي بتنقل البيانات الي السيرفر قفلت ال SERVICE وشغلتها تاني نقلت البيانات تمام وشاشة الجرد اشتغلت

**Comment by mashh2017** [comment]
well done.

**Comment by mashh2017** [comment]
تاكد من وجود عمود يحمل الاسم ERROR_MESSAGE
في الجدةل hh_bcyc

**Comment by mohamed2020** [comment]
الرسالة  بتظهر معايا او ما ادخل شاشة لوحة التحكم وبتختفي لما بقفل السيرفس واشغلها بأيدي   MAS SYSTEM

**Comment by mashh2017** [comment]
ADD ERROR_MESSAGE COLUMN TO HH_BCYC TABLE
