### ISSUE TITLE
مشكلة اثناء حفظ الجرد 

### ISSUE THREAD

**Issue by mohamed2020** [mashhu/Hand-Held#20]
الرسالة : خطأ لا يوجد مسار مفتوح ل UNDEFINED/UNDEFINED  في    MAS 11.3

**Comment by mashh2017** [comment]
دي اثناء الحفظ 
؟

**Comment by mashh2017** [comment]
هل نزلت اخر CLIENT 
الجرد

**Comment by mohamed2020** [comment]
الرسالة بتظهر لما بضغط حفظ

**Comment by mohamed2020** [comment]
اخر جرد 11.4؟

**Comment by mashh2017** [comment]
نزل احدث سيرفر واحدث client 
مع حفظ النسخة الحالية من السيرفر وال client 

ملحوظة : شاشة القراءة  ربما تحتاج للرجوع الى شاشة القديمة من خلال اعادة تسمية الملف modifyReadingBulk-Assuit الى modifyReadingBulk

تحت فولدر ال templates

**Comment by mashh2017** [comment]
https://github.com/mashh2017/Hand-Held/releases/tag/client11.4
https://github.com/mashh2017/Hand-Held/releases/tag/11.4

**Comment by mohamed2020** [comment]
اللينك الاول فيه
https://github.com/mashh2017/Hand-Held/releases/tag/client11.4
 file واحد
 وده اللي موجود فيه
# مشروع الوحدات المحمولة
تسجيل ومتابعة ومناقشة المشاكل والمقترحات الخاصة ببرنامج الوحدات المحمولة

**Comment by mashh2017** [comment]
download client11.4.rar not source code

https://github.com/mashh2017/Hand-Held/releases/download/client11.4/client.11.4.rar
