### ISSUE TITLE
ادخال فاتورةاكثر من مرة اثناء الجرد

### ISSUE THREAD

**Issue by mohamed2020** [mashhu/Hand-Held#21]
اثناء الجرد في حالة إضافة فاتورة اكثر من مرة تظهر رسالة بان الفاتورة مضافة بالفعل ويظل رقم الفاتورة موجود في textbox
وعند جرد فاتورة اخري تظهر الفاتورة مضافة بالفعل ولا يقبل اي فاتورة اخري لا بعد ان يتم مسح كل ارقام الفواتير يدويا من 
textbox
فلو تتم اليا بحيث اذا كانت الفاتورة مضافة بالفعل تظهر رسالة ويختفي رقم الفاتورة كان افضل واسرع في الجرد

**Comment by mashh2017** [comment]
version 11.5
