### ISSUE TITLE
Version 11.5

### ISSUE THREAD

**Issue by mashh2017** [mashhu/Hand-Held#23]
ضبط الجرد
والحافظ التفصيلية

https://github.com/mashh2017/Hand-Held/releases/tag/Server11.5

https://github.com/mashh2017/Hand-Held/releases/tag/ClientVersion11.5

**Comment by mashh2017** [comment]
اي ملاحظات على الاصدار برجاء التعليق

**Comment by mohamed2020** [comment]
tested an run

**Comment by mohamed2020** [comment]
http://www.mediafire.com/file/9olfm9ubb54up8f/MAS_SYSTEMS_11.5.rar   



الملف بالكامل

**Comment by mohamed2020** [comment]
شاشة اعادة فتح مجموعة للتحصيل لا تقم بتنفيذ المطلوب منها
تظهر رسالة تقول تم
وفي شاشة الجرد تظهر رسالة لا توجد دورة مفتوحة لهذاالمسار
وده الحل اللي عملته واشتغل
update HH_BCYC
set GARD=null,
GARD_OK=null,
CLOSE_DATE_C=null,
ISCYCLE_COMPLETED_C=null
where BOOK_NO in('50211401','50211502','50240403','50241701','50222201','50222101')
and BILNG_DATE='2017-06-30'

**Comment by osamamohammed731** [comment]
نفس الحاله حصلت معايا و اضطريت اعمل نفس الحل علشان اشغل التحصيل تاني 
وكان الاصدار اقدم من 11.5
واضح انها مشكله قديمه بس محدش قابلها قبل كدا

**Comment by mohamed2020** [comment]
في مشكلة معايا في ترحيل التحصيل
لما ادخل صفحة ترحيل التحصيل واحمل كل البيانات يظهر في الصفحة 5 مسارات فقط وليس الكل

**Comment by ahmed-2017** [comment]
تقرير الفواتير المرتدة لمسار يظهر به رسالة خطأ عند كتابة رقم السجل والمسار 
تظهر 
"لا توجد دورة مفتوحة"

**Comment by mohamed2020** [comment]
لف دورة جديدة للعداد غير موجودة في تعديل القراءة لعميل ولا تعمل في شاشة تعديل تغيير حالة عداد
