### ISSUE TITLE
تقرير القراءات المرتفعة و مؤشر اداء مجموعة وبدون تعامل - الفيوم

### ISSUE THREAD

**Issue by Mostafa-Abdallah** [mashhu/Hand-Held#24]
الفيوم 

- القراءات المرتفعة
اضافة اختيار الكشاف والمجموعة وترك كتابة المسار اختيارى ليظهر التقرير المجموعة بمساراتها لكل كشاف بدلا من طباعتها مسار مسار.
- مؤشر اداء مجموعة 
اضافة الاطلاع على دورات سابقة او الدورة الحالية بعد اغلاق مسارات القراءة.
-بدون تعامل 
اضافة اختيار الكشاف والمجموعة وترك كتابة المسار اختيارى ليظهر التقرير المجموعة بمساراتها لكل كشاف بدلا من طباعتها مسار مسار.

**Comment by mohamed2020** [comment]
اسيوط
مؤشر اداء محصل لا يظهر بيانات لكل المحصلين
