### ISSUE TITLE
مشكلة يوجد مسارات مسجل انها مازالت مفتوحة على الوحدة - الفيوم-ابشواي

### ISSUE THREAD

**Issue by ahmed-2017** [mashhu/Hand-Held#32]
ظهور رسالة على الوحدة المحمولة 
"مشكلة يوجد مسارات مسجل انها مازالت مفتوحة على الوحدة "
وذلك عند إستقبال دورة جديدة

 مع العلم أن كل المسارات  تم عمل إنهاء دورة لها على الوحدة المحمولة وبالرجوع إلى قاعدة البيانات 
SQL 
نجد أن إحدى الـ
 Flalgs 
تكون ب صفر والاخرى بـ واحد أو العكس  
ISCLOSED_INDEVICE_C   ,     ISCLOSED_INDEVICE_R

**Comment by Mostafa-Abdallah** [comment]
المشكلة غير مقتصرة على فرع ابشواى فقط
