### ISSUE TITLE
شاشة الجرد -  الفيوم

### ISSUE THREAD

**Issue by Mostafa-Abdallah** [mashhu/Hand-Held#39]
- فى شاشة الجرد 
اولا : مشكلة لا يوجد مسار مفتوح عند اختيار المحصل 
ثانيا: عند طباعة ما تم جرده لا يظهر اسم المحصل و من قام بجرد الفواتير
ثالثاً: تاريخ الجرد غير مضبوط 
رابعاً: عند الضغط على اتمام الجرد واغلاق التحصيل تظهر رسالة بانه لم يتم انهاء الدورة للمسارات على الوحدة علما بان المحصل يعمل بالقراءات ولا يريد انهاء الدورة
خامساً : عند طباعة ما تم جرده اختيار طباعة ملخص بكل مجموعة ومساراتها وعدد ما تم جرده و مبلغ الفواتير
سادساً : عند وجود اكثر من مجموعة مع المحصل الواحد ويريد جرد مجموعة واحدة لابد من الجرد مسار مسار الرجاء اضافة امكانية اختيار اسم المحصل ومجموعة من المجاميع الخاصة به بمساراتها بدلا من الجرد مسار مسار

**Comment by HassanAbdelzaher** [comment]
تم الحل في اصدار 12.0
