### ISSUE TITLE
الرجاء ضبط اختيار صلاحيات المستخدمين - الفيوم

### ISSUE THREAD

**Issue by Mostafa-Abdallah** [mashhu/Hand-Held#46]
1- عند اختيار مشرف القراءات : 
(يتم فتح تجهيز البيانات واغلاق مسار القراءة فقط) ---- الرجاء اضافة سحب القراءة وترحيل القراءة ايضا.
2- عند اختيار مشرف التحصيل :
(يتم فتح تجهيز البيانات واغلاق مسار التحصيل والجرد فقط) ---- الرجاء اضافة سحب التحصيل وترحيل التحصيل ايضا والغاء الجرد بحيث يتم اختياره منفردا .
********* لانه عندما يتم  اختيار ادارة النظام يتم فتح القراءة والتحصيل معاً ********* 
3- عند اختيار حالة المسارات : 
(يتم فتح حالة المجموعات فى الفواتير ووحدة مراقبة المسارات والجرد ) ---- الرجاء الغاء الجرد بحيث يتم اختياره منفردا .
4- عند اختيار صيانة النظام :
تفتح للقراءة والتحصيل معاً ----- الرجاء فصل القراءة عن التحصيل

**Comment by HassanAbdelzaher** [comment]
سيتم ضبطها ان شاء الله في الكلينت القدام الاسبوه القادم

**Comment by HassanAbdelzaher** [comment]
تم فصبهم بالفعل في الاصدار 12.9
