### ISSUE TITLE
الرجاء اضافة الاستعلام برقم الاشتراك (((((((((هام جداً))))))))  - الفيوم 

### ISSUE THREAD

**Issue by Mostafa-Abdallah** [mashhu/Hand-Held#51]

**Comment by HassanAbdelzaher** [comment]
ماشي ان شاء الله الخميس يكون موجود في اخر  build

بس النسخة القادمة مهم جدا الاختيار فيها لسبب مهم جداا وهو انه حدثت بعض التغيير بالنسخة لتلائم العمل مع اكثر من نظام فواتير

**Comment by Mostafa-Abdallah** [comment]
وياريت يكون فيها كمان :
-اضافة رقم الاشتراك ليظهر فى تعديل القراءة لمسار .
- اضافة تعديل القراءة برقم الاشتراك فى تعديل القراءة ايضاً.

**Comment by HassanAbdelzaher** [comment]
تم اضافة البحث برقم العقار (الاشتراك)
في شاشة البحث 
- تم اضافة البحث برقم العداد مكون من كودالعداد مظاف اليه مرجع العداد

**Comment by Mostafa-Abdallah** [comment]
شكرا
لو ينفع كمان اضافة امكانية تعديل القراءة برقم الاشتراك بدلا من معرفة رقم الحساب من ايدامس وبعدين تعديل القراءة فى ماس
