### ISSUE TITLE
عند طباعة ما تم جرده اختيار طباعة ملخص بكل مجموعة ومساراتها وعدد ما تم جرده و مبلغ الفواتير -الفيوم

### ISSUE THREAD

**Issue by mashh2017** [mashhu/Hand-Held#55]
الرجاء عمل تفصيلي لتقرير ملخص الجرد يظهر به الإجمالي فواتير ومبلغ لكل مسار على حدا *
وملخص للإجمالي *

**Comment by HassanAbdelzaher** [comment]
تم تغيير كبير بشاشة الجرد
شكل التقرير
[Untitled Document.pdf](https://github.com/mashhu/Hand-Held/files/1584007/Untitled.Document.pdf)

**Comment by HassanAbdelzaher** [comment]
بس ما زال التقرير على مستوى المحصل
