### ISSUE TITLE
الفيوم - V 13.70 - Errors 

### ISSUE THREAD

**Issue by Mostafa-Abdallah** [mashhu/Hand-Held#62]
@HassanAbdelzaher 
-  تعديل القراءة لمسار

![un](https://user-images.githubusercontent.com/30770255/37282146-128a8590-25fc-11e8-935c-5dc3f744216c.png)

**Comment by ahmed-2017** [comment]
لحل المشكلة برجاء تنزيل إصدار 13.73

https://github.com/mashhu/Hand-Held/releases/tag/13.73

**Comment by Mostafa-Abdallah** [comment]
- عند ترحيل الجرد 
لا يقبل ترحيل كل المسارات مرة واحده .

![img_20180311_120327](https://user-images.githubusercontent.com/30770255/37300603-074fe4f8-262f-11e8-8dcc-fa97c599aa9d.jpg)

**Comment by Mostafa-Abdallah** [comment]
- عند جرد اى فاتورة تظهر رسالة (خطأ داخلى تكرار) وفى نفس الوقت يتم جردها وتظهر فى الجانب الايسر

![img_20180311_114459](https://user-images.githubusercontent.com/30770255/37367022-dfe0e25a-270a-11e8-970f-0db98efa61d3.jpg)
