### ISSUE TITLE
نصف  تقارير التحصيل لا تعمل - الفيوم

### ISSUE THREAD

**Issue by Mostafa-Abdallah** [mashhu/Hand-Held#67]
- التحصيل على مستوى المجموعة .
- التحصيل على مستوى المحصل.
- التحصيل على مستوى النشاط.
- التحصيل على مستوى اليوم .
- التحصيل على مستوى اليوم لمحصل.
- التحصيل على مستوى الشرائح.
- التحصيل على مستوى الشرائح لكشاف.
- التحصيل على مستوى المسارات.
- ملاحظات التحصيل.
- ملاحظات التحصيل لمحصل .
- الفواتير المرتدة لمسار .

![untitled11](https://user-images.githubusercontent.com/30770255/39396820-b5ac4f92-4af5-11e8-9333-0f05603955a1.png)

---------------------------------------------------------------------------------------------------------

**Comment by ahmed-2017** [comment]
التحصيل على مستوى المجموعة بيظهر نتائج في 
network 
لكن مش بيعرض نتائج وبيظهر خطأ
an error has occured

http://localhost/#/reports/collectionPerBg

**Comment by ahmed-2017** [comment]
التحصيل على مستوى المحصل **مش**  بيظهر نتائج في 
network 
 ومش بيعرض نتائج وبيظهر خطأ
an error has occured

http://localhost/#/reports/collectionPerEmp

**Comment by ahmed-2017** [comment]
التحصيل على مستوى النشاط بيظهر نتائج في
network
لكن مش بيعرض نتائج وبيظهر خطأ
an error has occured

http://localhost/#/reports/collectionPerCtg

**Comment by ahmed-2017** [comment]
التحصيل على مستوى اليوم بيظهر نتائج في
network
لكن مش بيعرض نتائج وبيظهر خطأ
an error has occured

http://localhost/#/reports/collectionPerDay

**Comment by ahmed-2017** [comment]
التحصيل على مستوى اليوم لمحصل # **مش** بيظهر نتائج في
network
ومش بيعرض نتائج وبيظهر خطأ
an error has occured

http://localhost/#/reports/collectionPerDayPerEmp

**Comment by ahmed-2017** [comment]
التحصيل على مستوى الشرائح **و مش** بيظهر نتائج في
network
ومش بيعرض نتائج وبيظهر خطأ
an error has occured

http://localhost/#/reports/collectionPerBand

**Comment by ahmed-2017** [comment]
التحصيل على مستوى الشرائح لكشاف. **و مش** بيظهر نتائج في
network
ومش بيعرض نتائج وبيظهر خطأ
an error has occured

http://localhost/#/reports/collectionPerBandEmp

**Comment by ahmed-2017** [comment]
التحصيل على مستوى المسارات. **و مش** بيظهر نتائج في
network
ومش بيعرض نتائج وبيظهر خطأ
an error has occured

http://localhost/#/reports/collectionForBook

**Comment by ahmed-2017** [comment]
ملاحظات التحصيل. **و مش** بيظهر نتائج في
network
ومش بيعرض نتائج وبيظهر خطأ
an error has occured

http://localhost/#/reports/collectionNotes

**Comment by ahmed-2017** [comment]
ملاحظات التحصيل لمحصل. و مش بيظهر نتائج في
network
ومش بيعرض نتائج وبيظهر خطأ
an error has occured

http://localhost/#/reports/collectionNotesForEmp

**Comment by ahmed-2017** [comment]
ملاحظات التحصيل لمحصل. و مش بيظهر نتائج في
network
ومش بيعرض نتائج وبيظهر خطأ
"برجاء اختيار المحصل"

http://localhost/#/reports/unbilled
