### ISSUE TITLE
اذا كانت بعض تقارير التحصيل لا تعمل برجاء تحميل اخر اصدار من برنامج ماس -الفيوم وباقي المواقع

### ISSUE THREAD

**Issue by ahmed-2017** [mashhu/Hand-Held#68]
اذا كانت بعض تقارير التحصيل لا تعمل برجاء تحميل اخر اصدار من برنامج ماس -الفيوم وباقي المواقع

version 14.7

واخر اصدار من ال
client

**Comment by mohamed2020** [comment]
أخر إصدار من client 14.6

**Comment by Mostafa-Abdallah** [comment]
اخر Client ايه تحديدا 
وينفع انزله على الـ  version  الموجود  ولا لازم انزل الـ version  الجديد
