### ISSUE TITLE
مطلوب تقرير بعدد التوريدات خلال الدورة - الفيوم 

### ISSUE THREAD

**Issue by Mostafa-Abdallah** [mashhu/Hand-Held#84]
@HassanAbdelzaher 

الرجاء اضافة تقرير بعدد التوريدات لكل محصل خلال الدورة (سطر لكل توريدة بالعدد والمبلغ والقسيمة)
ويكون التقرير مشابه لتقرير (((سجل التوريدات))) الموجود

بالاضافة لما تم طلبه سابقاً 
https://github.com/mashhu/Hand-Held/issues/79

**Comment by HassanAbdelzaher** [comment]
جاري عمل التقارير الاضافية

**Comment by HassanAbdelzaher** [comment]
version 15
https://github.com/mashhu/Hand-Held/releases/tag/15.0

**Comment by HassanAbdelzaher** [comment]
version 15
https://github.com/mashhu/Hand-Held/releases/tag/15.0
